apiVersion: v1
data:
  db.sh: |
    #!/bin/bash

    psql -h postgresql-primary.default.svc.cluster.local -U postgres -c "CREATE USER $POSTGRES_REPLICATION_USERNAME WITH REPLICATION ENCRYPTED PASSWORD '$POSTGRES_REPLICATION_PASSWORD'"
    psql -h postgresql-primary.default.svc.cluster.local -U postgres -f /script/init-db.sql
  init-db.sql: |
    CREATE DATABASE refapp;

    \c refapp

    CREATE TABLE records(
       ID SERIAL PRIMARY KEY,
       created_at     timestamp  NOT NULL,
       data           CHAR(255),
       host           CHAR(255)  NOT NULL
    );

    do $$
    begin
    for r in 1..10 loop
    INSERT INTO records (data, host, created_at) values ('test', 'prefill', now());
    end loop;
    end;
    $$;
kind: ConfigMap
metadata:
  name: db-init-script
