apiVersion: v1
data:
  pg-init.sh: "#!/bin/bash\n\nPGDATA=/var/lib/postgresql/data/pgdata\nPODINFO_LABELS_FILE=/etc/podinfo/labels\n\nif
    [ ! -d $PGDATA ] \nthen\n  echo \"The postgresql data directory $PGDATA does not
    exist.\"\n\n  if [ ! -e $PODINFO_LABELS_FILE ]\n  then\n    echo \"  The podinfo
    file $PODINFO_LABELS_FILE does not exist. Did you create a downward API volume?\"
    \n    echo \"  Exitting with a failure.\"\n    exit 1\n  fi\n\n  cat $PODINFO_LABELS_FILE\n\n
    \ if grep -q 'statefulset.kubernetes.io/pod-name=\"postgresql-sts-0\"' $PODINFO_LABELS_FILE\n
    \ then\n    echo \"  Identified this Pod to be the static primary: postgresql-sts-0.\"\n
    \   echo \"  Executing initdb...\"\n    initdb --username postgres --pwfile <(echo
    $POSTGRES_PASSWORD)\n    if [ $? -ne 0 ] \n    then\n      echo \"  Failed to
    execute initdb.\"\n      exit 1\n    fi\n  else\n    echo \"  Identified this
    Pod to a secondary.\"\n    echo \"  Executing pg_basebackup...\"\n    /usr/local/bin/pg_basebackup
    -h postgresql-primary.default.svc.cluster.local -U replicator -p 5432 -D $PGDATA
    -Fp -Xs -R\n    if [ $? -ne 0 ] \n    then\n      echo \"  Failed to execute pg_basebackup.\"\n
    \     exit 1\n    fi\n  fi\n  echo \"  Done.\"  \nelse\n  echo \"Found the postgresql
    data directory at $PGDATA.\"\nfi\n\necho \"Starting PostgreSQL...\"\nchmod 700 -R /var/lib/postgresql/data/pgdata
    \n/usr/local/bin/postgres -c config_file=/etc/postgresql/postgresql.conf -D $PGDATA\n\n"
kind: ConfigMap
metadata:
  name: postgresql-utils
