apiVersion: v1
kind: Service
metadata:
  name: postgresql-primary
  labels:
    app: postgresql-server
    rolv: primary
spec:
  ports:
  - port: 5432
    name: postgresql-port
  clusterIP: None
  selector:
      app: postgresql-server
      # role: primary
      statefulset.kubernetes.io/pod-name: postgresql-sts-0
